version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:17.2.0 # the primary container, where your job's commands are run
        auth:
          username: mehdidi13
          password: $DOCKERHUB_PASSWORD # context / project UI env-var reference
    steps:
      - checkout # check out the code in the project directory
      - run: docker build . -t mehdidi13/circleci-web-app
          docker run -p 49160:8080 -d mehdidi13/circleci-web-app
          echo "dockerisation complete ?" # run the `echo` command
